# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables: 
  ZLIB_COMMON:        1.2.11
  HDF5_COMMON:        1.10.5
  NETCDF_C_NEW:       4.7.1
  NETCDF_FORTRAN_NEW: 4.4.5
  NETCDF_C_OLD:       4.1.3

# Images to build
strategy:
  matrix:
    # gcc4:
    #   GCC_VERSION: 4
    #   ZLIB_VERSION: $(ZLIB_COMMON)
    #   HDF5_VERSION: $(HDF5_COMMON)
    #   NETCDF_C_VERSION: $(NETCDF_C_NEW)
    #   NETCDF_FORTRAN_VERSION: $(NETCDF_FORTRAN_NEW)
    # gcc5:
    #   GCC_VERSION: 5
    #   ZLIB_VERSION: $(ZLIB_COMMON)
    #   HDF5_VERSION: $(HDF5_COMMON)
    #   NETCDF_C_VERSION: $(NETCDF_C_NEW)
    #   NETCDF_FORTRAN_VERSION: $(NETCDF_FORTRAN_NEW)
    # gcc6:
    #   variables:
    #   GCC_VERSION: 6
    #   ZLIB_VERSION: $(ZLIB_COMMON)
    #   HDF5_VERSION: $(HDF5_COMMON)
    #   NETCDF_C_VERSION: $(NETCDF_C_NEW)
    #   NETCDF_FORTRAN_VERSION: $(NETCDF_FORTRAN_NEW)
    gcc7:
      variables:
      GCC_VERSION: 7
      ZLIB_VERSION: $(ZLIB_COMMON)
      HDF5_VERSION: $(HDF5_COMMON)
      NETCDF_VERSION:
      NETCDF_C_VERSION: $(NETCDF_C_NEW)
      NETCDF_FORTRAN_VERSION: $(NETCDF_FORTRAN_NEW)
    # gcc8:
    #   variables:
    #   GCC_VERSION: 8
    #   ZLIB_VERSION: $(ZLIB_COMMON)
    #   HDF5_VERSION: $(HDF5_COMMON)
    #   NETCDF_C_VERSION: $(NETCDF_C_NEW)
    #   NETCDF_FORTRAN_VERSION: $(NETCDF_FORTRAN_NEW)
    # gcc9:
    #   variables:
    #   GCC_VERSION: 9
    #   ZLIB_VERSION: $(ZLIB_COMMON)
    #   HDF5_VERSION: $(HDF5_COMMON)
    #   NETCDF_C_VERSION: $(NETCDF_C_NEW)
    #   NETCDF_FORTRAN_VERSION: $(NETCDF_FORTRAN_NEW)
    gcc7-old-netcdf:
      variables:
      GCC_VERSION: 7
      ZLIB_VERSION: $(ZLIB_COMMON)
      HDF5_VERSION: $(HDF5_COMMON)
      NETCDF_VERSION:   4.1.2
      NETCDF_C_VERSION: 4.1.2
      NETCDF_FORTRAN_VERSION: none
# Steps to build images
steps:
- task: Docker@2
  displayName: Login to Docker Hub
  inputs:
    command: login
    containerRegistry: DockerHub
- task: Docker@2
  displayName: Build image
  inputs:
    command: build
    repository: liambindle/gcc-netcdf-c-netcdf-fortran
    tags: $(GCC_VERSION)-$(NETCDF_C_VERSION)-$(NETCDF_FORTRAN_VERSION)
    arguments: |
      --build-arg GCC_VERSION=$(GCC_VERSION)
      --build-arg ZLIB_VERSION=$(ZLIB_VERSION) 
      --build-arg HDF5_VERSION=$(HDF5_VERSION) 
      --build-arg NetCDF_C_VERSION=$(NETCDF_C_VERSION)
      --build-arg NetCDF_Fortran_VERSION=$(NETCDF_FORTRAN_VERSION)
      --build-arg NetCDF_VERSION=$(NETCDF_VERSION)
- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: DockerHub
    repository: liambindle/gcc-netcdf-c-netcdf-fortran
    command: push
    tags: |
      $(GCC_VERSION)-$(NETCDF_C_VERSION)-$(NETCDF_FORTRAN_VERSION)
  
