# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

strategy:
  matrix:
    gcc5:
      GCC_VERSION: 5
      ZLIB_VERSION: 1.2.11
      HDF5_VERSION: 1.10.5
      NetCDF_C_VERSION: 4.7.1
      NetCDF_Fortran_VERSION: 4.4.5
    gcc6:
      variables:
      GCC_VERSION: 6
      ZLIB_VERSION: 1.2.11
      HDF5_VERSION: 1.10.5
      NetCDF_C_VERSION: 4.7.1
      NetCDF_Fortran_VERSION: 4.4.5

steps:
- script: |
    echo Building container for gcc-$(GCC_VERSION)!
    ./build.sh
  displayName: 'Building container'
